const { createClient } = require('@supabase/supabase-js')

const SUPABASE_URL = process.env.SUPABASE_URL?.trim().replace(/^["']|["']$/g, '')
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY?.trim().replace(/^["']|["']$/g, '')

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('CRITICAL: Missing Supabase credentials for candidates API')
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

module.exports = async function handleCandidates(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({
      success: false,
      error: 'Method not allowed'
    })
  }

  try {
    const {
      // Contact Info (SENSITIVE)
      full_name,
      national_id,
      mobile,
      email,
      // Basic Info
      nationality,
      gender,
      age,
      marital_status,
      has_driving_license,
      owns_car,
      country,
      city,
      district,
      // Legal Status
      military_status,
      has_previous_court_judgments,
      has_criminal_record_document,
      registered_in_social_insurance,
      has_labor_cases,
      // Education
      education_level,
      education_specialization,
      // Professional
      functional_sector,
      current_job_title,
      total_experience_years,
      current_salary,
      expected_salary,
      // Related data
      experiences,
      languages,
      computer_skills
    } = req.body

    // Validation - Required fields
    if (!full_name || !mobile || !email) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: full_name, mobile, email'
      })
    }

    // Server-side validation - Additional required fields for data quality
    if (!nationality) {
      return res.status(400).json({
        success: false,
        error: 'الجنسية مطلوبة - Nationality is required'
      })
    }

    if (!gender) {
      return res.status(400).json({
        success: false,
        error: 'الجنس مطلوب - Gender is required'
      })
    }

    if (!city) {
      return res.status(400).json({
        success: false,
        error: 'المدينة مطلوبة - City is required'
      })
    }

    if (!education_level) {
      return res.status(400).json({
        success: false,
        error: 'المستوى التعليمي مطلوب - Education level is required'
      })
    }

    if (!functional_sector) {
      return res.status(400).json({
        success: false,
        error: 'القطاع الوظيفي مطلوب - Functional sector is required'
      })
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid email format'
      })
    }

    // Validate mobile format (basic)
    if (mobile.length < 10) {
      return res.status(400).json({
        success: false,
        error: 'Invalid mobile number'
      })
    }

    // Insert candidate profile
    // Note: candidate_code will be auto-generated by trigger
    const { data: candidateData, error: candidateError } = await supabase
      .from('candidate_profiles')
      .insert({
        full_name,
        national_id,
        mobile,
        email,
        nationality,
        gender,
        age: age ? parseInt(age) : null,
        marital_status,
        has_driving_license: has_driving_license === true || has_driving_license === 'true',
        owns_car: owns_car === true || owns_car === 'true',
        country,
        city,
        district,
        military_status,
        has_previous_court_judgments: has_previous_court_judgments === true || has_previous_court_judgments === 'true',
        has_criminal_record_document: has_criminal_record_document === true || has_criminal_record_document === 'true',
        registered_in_social_insurance: registered_in_social_insurance === true || registered_in_social_insurance === 'true',
        has_labor_cases: has_labor_cases === true || has_labor_cases === 'true',
        education_level,
        education_specialization,
        functional_sector,
        current_job_title,
        total_experience_years: total_experience_years ? parseInt(total_experience_years) : null,
        current_salary: current_salary ? parseFloat(current_salary) : null,
        expected_salary: expected_salary ? parseFloat(expected_salary) : null,
        verification_status: 'pending',
        premium_badge: false,
        status: 'new'
      })
      .select()

    if (candidateError) {
      console.error('Candidate insert error:', candidateError.message)
      return res.status(500).json({
        success: false,
        error: 'Failed to submit candidate registration'
      })
    }

    const candidateId = candidateData[0].id

    // Insert experiences (up to 4)
    if (experiences && Array.isArray(experiences) && experiences.length > 0) {
      const experiencesData = experiences.slice(0, 4).map((exp, index) => ({
        candidate_id: candidateId,
        company_name: exp.company_name,
        job_title: exp.job_title,
        job_tasks: exp.job_tasks,
        from_date: exp.from_date,
        to_date: exp.to_date,
        sort_order: index
      }))

      const { error: expError } = await supabase
        .from('candidate_experiences')
        .insert(experiencesData)

      if (expError) {
        console.error('Experiences insert error:', expError.message)
      }
    }

    // Insert languages (up to 3)
    if (languages && Array.isArray(languages) && languages.length > 0) {
      const languagesData = languages.slice(0, 3).map((lang, index) => ({
        candidate_id: candidateId,
        language: lang.language,
        level: lang.level,
        sort_order: index
      }))

      const { error: langError } = await supabase
        .from('candidate_languages')
        .insert(languagesData)

      if (langError) {
        console.error('Languages insert error:', langError.message)
      }
    }

    // Insert computer skills
    // Convert object format { excel: "جيد", word: "ممتاز", powerpoint: "جيد جدا" }
    // to array format [{ skill: "Excel", level: "جيد" }, ...]
    if (computer_skills && typeof computer_skills === 'object') {
      const skillsArray = []
      
      if (computer_skills.excel) {
        skillsArray.push({ skill: 'Excel', level: computer_skills.excel })
      }
      if (computer_skills.word) {
        skillsArray.push({ skill: 'Word', level: computer_skills.word })
      }
      if (computer_skills.powerpoint) {
        skillsArray.push({ skill: 'PowerPoint', level: computer_skills.powerpoint })
      }

      if (skillsArray.length > 0) {
        const skillsData = skillsArray.map((skill, index) => ({
          candidate_id: candidateId,
          skill: skill.skill,
          level: skill.level,
          sort_order: index
        }))

        const { error: skillsError } = await supabase
          .from('candidate_computer_skills')
          .insert(skillsData)

        if (skillsError) {
          console.error('Computer skills insert error:', skillsError.message)
        }
      }
    }

    return res.status(200).json({
      success: true,
      message: 'تم تسجيل بياناتك بنجاح. سيتم مراجعة ملفك الشخصي من قبل فريقنا المتخصص.',
      data: {
        candidate_code: candidateData[0].candidate_code,
        id: candidateData[0].id
      }
    })
  } catch (error) {
    console.error('Candidates API error:', error.message)
    return res.status(500).json({
      success: false,
      error: 'Internal server error'
    })
  }
}
